### ISSUE TITLE
Problem with custom translatable model redirection

### ISSUE THREAD

**Issue by cchapleau** [asdoria/AsdoriaSyliusLocaleSwitcherPlugin#4]
Hi,

I'm on :
     - Sylius `1.12.16`
     - Symfony `6.4.8`
     - PHP `8.2.18`

With a custom translatable model, I have troubles with the redirection in the show part.

Here is an example to explain it :

`✅` from .../fr/actualite to .../en/actutality :
```
app_front_actuality_index:
    path:
        fr: /{_locale}/actualite
        en: /{_locale}/actuality
    methods: [GET]
    defaults:
        _controller: app.controller.actuality::actuality_index
```
`❌` from .../fr/actualite/mon-premier-article to .../en/actuality/my-first-article :
```
app_front_actuality_show:
    path:
        fr: /{_locale}/actualite/{slug}
        en: /{_locale}/actuality/{slug}
    methods: [GET]
    defaults:
        _controller: app.controller.actuality::actuality_show
```
I notice that when debugging my route `app_front_actuality_show`, the alias is null.
Is it normal that it doesn't work for me or I've done something wrong with the plugin ?
Or maybe, my custom translatable model's configuration miss something ?

Thank you so much in advance for your reply and your help.
